service: Lab7
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  memorySize: 300
  timeout: 10
  architecture: x86_64
  stackTags:
    terraform: "false"
    type: "kinesistest"

useDotenv: true

functions:
  hello:
    handler: handler.hello
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - KinesisDataStream
              - Arn

# you can add CloudFormation resource templates here
resources:
  Resources:
    KinesisDataStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:STREAM_NAME}
        RetentionPeriodHours: 24
        StreamModeDetails:
          StreamMode: ON_DEMAND
  Outputs:
    KinesisArn:
      Description: ARN of the stream
      Value:
        Fn::GetAtt:
          - KinesisDataStream
          - Arn
        
