service: Lab3
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

plugins:
  - serverless-lift

functions:
  sqsinvoke:
    handler: handler.sqsInvoker
    environment:
      QUEUE_URL: ${construct:testqueue.queueUrl}
    events:
      - schedule: rate(1 minute)

constructs:
    testqueue:
        type: queue
        worker:
            handler: handler.queueHandler

